-- 코드를 입력하세요
SELECT info.FLAVOR
FROM FIRST_HALF fh
JOIN ICECREAM_INFO info ON fh.FLAVOR = info.FLAVOR
WHERE fh.TOTAL_ORDER > 3000 AND info.INGREDIENT_TYPE = 'fruit_based'
ORDER BY fh.TOTAL_ORDER DESC;